// Local fallback task pool - migrated from reference/index.html
import type { Task } from "./llm/types";

export const LOCAL_TASKS: Task[] = [
  { id: 1, category: "文学", minutes: "5–10", text: "打开 Poetry Foundation 首页，读第一首出现的诗。", soft: "不需要读完，只需要开始。" },
  { id: 2, category: "文学", minutes: "5–15", text: "在维基百科查\u201C今天出生的诗人\u201D，选名字最顺眼的读一首。", soft: "随便选就好。" },
  { id: 3, category: "文学", minutes: "5", text: "随机翻开一本你身边的书，只读当前页最喜欢的一句话。", soft: "只要一句就够了。" },
  { id: 4, category: "文学", minutes: "5–10", text: "在 YouTube 搜\u201Cpoem reading\u201D，随便点开一个视频听1首朗读。", soft: "听到哪儿算哪儿。" },
  { id: 5, category: "好奇心", minutes: "5–10", text: "拿起家里一份说明书，读完其中一段你从没读过的部分。", soft: "读懂一点点就赢了。" },
  { id: 6, category: "艺术", minutes: "5–10", text: "打开 Google Arts & Culture，看首页第一幅画30秒，然后只说出一个颜色。", soft: "只看颜色，不求意义。" },
  { id: 7, category: "写作", minutes: "2–5", text: "在备忘录写一句\u201C今天最真实的感受\u201D（只写一句，不解释）。", soft: "一句就够了。" },
  { id: 8, category: "写作", minutes: "5–10", text: "把一句你喜欢的句子改写得更短一点（删掉一半也可以）。", soft: "删减就是力量。" },
  { id: 9, category: "艺术", minutes: "5–15", text: "查\u201C今天是哪位画家的忌日/生日\u201D，看他/她的一幅作品并放大细节。", soft: "看细节比看全貌更轻松。" },
  { id: 10, category: "文学", minutes: "5–10", text: "读一段法语或葡语短诗：不查词典，只读两遍，感受声音。", soft: "听懂与否都没关系。" },
  { id: 11, category: "家庭", minutes: "2–5", text: "把宝宝此刻的一个表情用三个形容词记录下来。", soft: "这是你们的私人词典。" },
  { id: 12, category: "音乐", minutes: "5–10", text: "播放德彪西《月光》或巴赫平均律，闭眼听其中一小段。", soft: "只听，不做别的。" },
  { id: 13, category: "艺术", minutes: "5–10", text: "在纸上随便画五条线，再把它们变成一幅小画（加两个点也算）。", soft: "不求像，只求出现。" },
  { id: 14, category: "音乐", minutes: "5", text: "找一首你十年前喜欢的歌，只听前30秒。", soft: "让旧时光来抱你一下。" },
  { id: 15, category: "写作", minutes: "5–10", text: "把今天的天气写成一句\u201C小说开头\u201D。", soft: "你只需要开头。" },
  { id: 16, category: "文学", minutes: "5", text: "打开《Os Maias》电子版，随机滑动停下，只读一句对话，不分析。", soft: "只听它的声音。" },
  { id: 17, category: "艺术", minutes: "5", text: "看一幅莫奈《睡莲》（任意版本），只观察颜色，不想意义。", soft: "只看颜色就很好。" },
  { id: 18, category: "文学", minutes: "10–20", text: "把一句中文诗翻译成葡语：先直译，再把它改得更像诗一点。", soft: "粗糙也很美。" },
  { id: 19, category: "写作", minutes: "2–5", text: "给未来的自己写一句话（只一句）。", soft: "一句就是一封信。" },
  { id: 20, category: "学术", minutes: "5–10", text: "读一段你的论文草稿：不修改，只朗读。", soft: "朗读能让文字呼吸。" },
  { id: 21, category: "好奇心", minutes: "5–10", text: "在维基百科打开一个随机词条，读5分钟。", soft: "读到哪里算哪里。" },
  { id: 22, category: "好奇心", minutes: "5", text: "在维基百科点击\u201C随机条目\u201D，只读第一段，不继续查下去。", soft: "停在第一段就很好。" },
  { id: 23, category: "学习", minutes: "10–20", text: "学一个新的法语动词变位：只练现在时或近未来。", soft: "只学一个时态就够了。" },
  { id: 24, category: "好奇心", minutes: "5–10", text: "看一个 5 分钟 TED-Ed 视频，结束后只记住一个词。", soft: "一个词就够了。" },
  { id: 25, category: "好奇心", minutes: "5–15", text: "查\u201C今天世界发生的一个科学发现/技术新闻\u201D，只读标题+第一段。", soft: "只读第一段就停。" },
  { id: 26, category: "学习", minutes: "10–15", text: "在词典里找一个陌生词，写一个很短的例句（10个字以内也行）。", soft: "短句更容易活下去。" },
  { id: 27, category: "学术", minutes: "10–20", text: "读一页文学理论书：只圈出一个关键词，写下你对它的直觉解释。", soft: "直觉先于严谨。" },
  { id: 28, category: "好奇心", minutes: "5–15", text: "查\u201C里斯本一条街道名字的来源\u201D，读完第一段。", soft: "你在和城市说话。" },
  { id: 29, category: "学习", minutes: "5–10", text: "学一个简单的日语表达（比如问候/谢谢），大声说三遍。", soft: "发音不完美也很好。" },
  { id: 30, category: "艺术", minutes: "5–10", text: "看一段艺术史时间线：只选一个年代停留1分钟。", soft: "停一下就够了。" },
  { id: 31, category: "好奇心", minutes: "5–10", text: "读一个很短的哲学小故事，然后写下你第一反应的一句话。", soft: "第一反应最诚实。" },
  { id: 32, category: "生活", minutes: "5–15", text: "查一个你常吃食物的营养结构（例如燕麦/酸奶/鸡蛋），只记住一个数字。", soft: "一个数字就足够。" },
  { id: 33, category: "生活", minutes: "5–10", text: "学一个新的电脑/手机快捷技巧：学完立刻用一次。", soft: "用一次就算学会。" },
  { id: 34, category: "好奇心", minutes: "5–10", text: "打开地图，找一个从没注意过的小国：只看它的形状和邻国。", soft: "世界会变得更大一点。" },
  { id: 35, category: "文学", minutes: "5–10", text: "查\u201C今天是哪位女性作家的纪念日/生日\u201D，读她的一段简介。", soft: "只读简介就停。" },
  { id: 36, category: "放松", minutes: "5–10", text: "学习一个新的呼吸法（比如4-7-8），只做两轮。", soft: "两轮足够改变一点点。" },
  { id: 37, category: "家庭", minutes: "5–10", text: "读一段关于婴儿发展的小科普：只读你最关心的那一段。", soft: "只读一段就好。" },
  { id: 38, category: "音乐", minutes: "5–10", text: "查一个音乐术语是什么意思（如\u201Ctempo/legato\u201D），并找一段示例听10秒。", soft: "听到就理解了一半。" },
  { id: 39, category: "学术", minutes: "5–10", text: "翻一页旧笔记，挑一个\u201C当时很重要\u201D的句子抄到新备忘录里。", soft: "把它带回今天。" },
  { id: 40, category: "写作", minutes: "2–5", text: "打开手机备忘录，写下此刻窗外最微小的一种声音（只写名词，不写句子）。", soft: "一个词也算完整。" },
  { id: 41, category: "放松", minutes: "3–5", text: "做3分钟深呼吸：吸4秒，停4秒，呼6秒，重复。", soft: "你在给身体一个信号。" },
  { id: 42, category: "放松", minutes: "5–10", text: "给自己泡一杯热茶：只专心闻味道10次。", soft: "闻味道就已经在休息。" },
  { id: 43, category: "放松", minutes: "5–10", text: "做5分钟肩颈拉伸：每个动作停留15秒。", soft: "轻一点就好。" },
  { id: 44, category: "放松", minutes: "2–5", text: "站在窗前看天空2分钟：只数云朵/鸟/光斑。", soft: "数一数就够了。" },
  { id: 45, category: "放松", minutes: "5–10", text: "听一段雨声或海浪白噪音：只听，不刷信息。", soft: "让声音替你撑一会儿。" },
  { id: 46, category: "放松", minutes: "5–10", text: "闭眼做身体扫描：从脚到头，哪里紧就轻轻放松哪里。", soft: "不需要放松完。" },
  { id: 47, category: "放松", minutes: "5", text: "涂护手霜并慢慢按摩双手：每根手指按压10秒。", soft: "手也需要被照顾。" },
  { id: 48, category: "放松", minutes: "5", text: "什么都不做，设5分钟计时器发呆。", soft: "发呆是合法的。" },
  { id: 49, category: "写作", minutes: "5–10", text: "写下今天\u201C已经做得很好的三件小事\u201D（再小都算）。", soft: "你比自己以为的更厉害。" },
  { id: 50, category: "家庭", minutes: "1–3", text: "看宝宝睡觉一分钟：只呼吸，不思考。", soft: "这是你们共同的安静。" },
  { id: 51, category: "生活", minutes: "2–5", text: "喝一整杯水：分三口慢慢喝完。", soft: "身体会记得这份温柔。" },
  { id: 52, category: "生活", minutes: "5–10", text: "整理桌面一个角落：只清出一块A4纸大小的空间。", soft: "一点点秩序就够了。" },
  { id: 53, category: "放松", minutes: "2–5", text: "洗一把脸或喷一点保湿：把水停留在皮肤上10秒。", soft: "让自己被照顾一下。" },
  { id: 54, category: "音乐", minutes: "5–10", text: "听一首完全不熟悉的音乐：只听1分钟后决定要不要继续。", soft: "你有随时停止的权利。" },
  { id: 55, category: "放松", minutes: "3–5", text: "轻轻伸展背部：猫牛式或前屈都行，30次呼吸以内结束。", soft: "温柔一点。" },
  { id: 56, category: "放松", minutes: "1–2", text: "对镜子里的自己笑10秒（哪怕是假笑也可以）。", soft: "身体会慢慢相信。" },
  { id: 57, category: "写作", minutes: "2–5", text: "写一句\u201C我现在允许自己慢一点\u201D。", soft: "允许本身就是力量。" },
  { id: 58, category: "放松", minutes: "1–3", text: "轻轻把双手放在胸口，感受心跳 1 分钟，不数时间，觉得够了就停。", soft: "你不需要证明什么。" },
  { id: 59, category: "放松", minutes: "2–5", text: "点一支你喜欢味道的香氛/蜡烛：只闻三次，然后关掉也可以。", soft: "一点点就够香。" },
  { id: 60, category: "放松", minutes: "1–2", text: "把肩膀放松下沉30秒，像把重物放到地上。", soft: "放下就很好。" },
  { id: 61, category: "生活", minutes: "5–10", text: "扔掉家里一个没用的东西（只扔一个）。", soft: "一个就够了。" },
  { id: 62, category: "帮助", minutes: "5–10", text: "回复一条你一直拖着的消息：只回一句核心内容。", soft: "一句就能解除悬而未决。" },
  { id: 63, category: "家庭", minutes: "2–5", text: "记录宝宝今天的一个新变化：一行字即可。", soft: "这是成长的证据。" },
  { id: 64, category: "生活", minutes: "5", text: "把一件衣服叠整齐并放回去。", soft: "完成感来自小动作。" },
  { id: 65, category: "生活", minutes: "5–10", text: "清理手机相册10张废图（只删10张）。", soft: "只删10张就停。" },
  { id: 66, category: "生活", minutes: "2–5", text: "写下一个待办事项，并在前面加一个\u201C最小下一步\u201D。", soft: "下一步比计划更重要。" },
  { id: 67, category: "生活", minutes: "10–20", text: "查一个你需要办理的行政信息：只找到\u201C办理入口/材料清单\u201D。", soft: "找到入口就停。" },
  { id: 68, category: "生活", minutes: "5–10", text: "给一封重要邮件草拟一句开头（只写第一句）。", soft: "第一句最难，你已经做了。" },
  { id: 69, category: "生活", minutes: "5", text: "整理包里的三样东西（只整理三样）。", soft: "三样就足够让你轻一点。" },
  { id: 70, category: "生活", minutes: "2–5", text: "看一下本周天气：只挑出一天最适合散步的时段。", soft: "挑出一天就够了。" },
  { id: 71, category: "生活", minutes: "10–20", text: "计划一顿简单健康的餐：写下\u201C主食+蛋白+蔬菜\u201D各一个。", soft: "写三样就完成。" },
  { id: 72, category: "生活", minutes: "2–5", text: "把水壶/饮水壶加满水。", soft: "未来的你会感谢现在的你。" },
  { id: 73, category: "生活", minutes: "5–10", text: "给未来一周写一个最小目标：一句话即可。", soft: "目标越小越容易发生。" },
  { id: 74, category: "学术", minutes: "5–10", text: "给论文文档改一个更清晰的标题或小标题（只改一个）。", soft: "改一个就很有效。" },
  { id: 75, category: "生活", minutes: "5–10", text: "备份一次手机照片/电脑文件：只做一次手动备份。", soft: "一次就够安心。" },
  { id: 76, category: "好奇心", minutes: "10–20", text: "查一个附近的新面包店/咖啡店，记下它的营业时间。", soft: "记下时间就停。" },
  { id: 77, category: "写作", minutes: "2–5", text: "记下一个突然想到的好点子：标题+一句解释。", soft: "留住火花。" },
  { id: 78, category: "生活", minutes: "5–10", text: "整理一个抽屉5分钟：计时一到立刻停。", soft: "停下也是完成。" },
  { id: 79, category: "生活", minutes: "2–5", text: "把床铺抚平：只抚平被子表面即可。", soft: "平整会让心也平一点。" },
  { id: 80, category: "放松", minutes: "10–20", text: "给自己安排一次短散步：出门走到一个路口再回来也算。", soft: "只要出门就赢了。" },
  { id: 81, category: "帮助", minutes: "2–5", text: "给一个朋友发一句\u201C我想到你了\u201D。", soft: "连接不需要长篇大论。" },
  { id: 82, category: "家庭", minutes: "2–5", text: "给父母发一张宝宝照片或一句近况。", soft: "一句就能让他们安心。" },
  { id: 83, category: "帮助", minutes: "5–10", text: "真诚回复一条别人关心你的消息：只回复你此刻的真实状态。", soft: "真实比完美重要。" },
  { id: 84, category: "放松", minutes: "1–3", text: "在心里祝福一个你在意的人：用一句话祝福即可。", soft: "祝福会回到你身上。" },
  { id: 85, category: "帮助", minutes: "2–5", text: "给伴侣写一句感谢（发出去或不发都可以）。", soft: "说出来就有力量。" },
  { id: 86, category: "帮助", minutes: "2–5", text: "给一位朋友的近况点个赞或留一句真心评论。", soft: "你在让世界更柔软。" },
  { id: 87, category: "家庭", minutes: "2–5", text: "给未来的孩子写一句话：关于\u201C我希望你知道……\u201D。", soft: "这是一份礼物。" },
  { id: 88, category: "放松", minutes: "2–5", text: "给过去的自己写一句安慰：像对朋友说话那样。", soft: "你也值得被安慰。" },
  { id: 89, category: "帮助", minutes: "2–5", text: "给一位老师/同学/同事发一句问候。", soft: "轻轻打个招呼就好。" },
  { id: 90, category: "帮助", minutes: "5–10", text: "把一条你觉得有用的信息分享给别人（链接/一句话都行）。", soft: "分享是温柔的行动。" },
  { id: 91, category: "放松", minutes: "1–2", text: "想起一个曾帮助你的人，在心里说一次\u201C谢谢\u201D。", soft: "感谢会让你变轻。" },
  { id: 92, category: "帮助", minutes: "1–2", text: "如果出门遇到邻居/店员，给一个微笑或一句简单问候。", soft: "你在练习柔软。" },
  { id: 93, category: "写作", minutes: "5", text: "写下一件今天让你感到被爱的事（哪怕很小）。", soft: "小也算爱。" },
  { id: 94, category: "放松", minutes: "2–5", text: "原谅一个小小的不愉快：对自己说\u201C这件事到这里就结束\u201D。", soft: "结束也是能力。" },
  { id: 95, category: "家庭", minutes: "1–3", text: "对宝宝轻声说一句温柔的话（描述他/她的存在即可）。", soft: "语言会成为拥抱。" },
  { id: 96, category: "放松", minutes: "1–2", text: "给世界写一句祝福（写在纸上或心里都可以）。", soft: "你正在参与温柔。" },
  { id: 97, category: "写作", minutes: "2–5", text: "记录一个今天的微小幸福瞬间：一句话+一个细节。", soft: "细节会留下来。" },
  { id: 98, category: "帮助", minutes: "2–5", text: "把一句你喜欢的话分享给一个人（或抄到自己的小本子）。", soft: "语言会流动。" },
  { id: 99, category: "放松", minutes: "2–5", text: "想象十年后的自己正在感谢现在的你：写下\u201C她感谢我因为……\u201D。", soft: "你正在为未来铺路。" },
  { id: 100, category: "放松", minutes: "1–2", text: "对自己说：\u201C慢慢来，也很好。\u201D", soft: "这句话永远有效。" },
];

export function getRandomTask(): Task {
  return LOCAL_TASKS[Math.floor(Math.random() * LOCAL_TASKS.length)];
}
